[workspace]
members = [
  "dnsparse",
  "esp-idf-bindgen",
  "esp32-hal",
  "app",
]

[profile.dev]
panic = "unwind"

[profile.release]
lto = true
panic = "unwind"
opt-level = "s"

[patch.crates-io]
libc = { git = "https://github.com/rust-lang/libc" }
