[workspace]
members = [
  "esp-idf-bindgen",
  "esp-idf-hal",
  "app",
]

[profile.dev]
panic = "unwind"

[profile.release]
lto = true
panic = "unwind"
opt-level = "s"

[patch.crates-io]
esp32-hal = { git = "https://github.com/esp-rs/esp32-hal" }
