on: [pull_request, push]

name: CI

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azohra/shell-linter@v0.3.0
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Dependencies
        run: |
          temp_dir="$(mktemp -d)"
          pushd "${temp_dir}"
          git clone -b xtensa https://github.com/reitermarkus/cross
          pushd cross

          pushd docker

          docker pull '${{ github.actor }}/cross:xtensa-esp32-none-elf' || true

          docker build \
            --cache-from '${{ github.actor }}/cross:xtensa-esp32-none-elf' \
            -t '${{ github.actor }}/cross:xtensa-esp32-none-elf' \
            -f Dockerfile.xtensa-esp32-none-elf \
            .

          popd

          cargo install --path . --force

          popd
          popd
          rm -rf "${temp_dir}"
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        run: ./build.sh
      - name: Log into Docker Hub
        run: echo '${{ secrets.DOCKER_TOKEN }}' | docker login -u '${{ github.actor }}' --password-stdin
      - name: Push Docker Image
        run: docker push '${{ github.actor }}/cross:xtensa-esp32-none-elf'
